sudo: false
language: perl
perl:
   - '5.18'
   - '5.20'
   - '5.22'
   - '5.24'
   - dev
   - 'blead'
matrix:
   allow_failures:
      - perl: dev
      - perl: 'blead'
   fast_finish: true
before_install:
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
   - export AUTOMATED_TESTING=1 NONINTERACTIVE_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
   - export AUTHOR_TESTING=0
   - git clone git://github.com/travis-perl/perl-travis-helper
   - source perl-travis-helper/init
   - build-perl
   - perl -V
install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - "dzil authordeps          --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest"
   - "dzil listdeps   --author --missing | grep -vP '[^\\w:]' | cpanm --verbose"
script:
   - dzil smoke --release --author
